server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service-route
            uri: "lb://USER-SERVICE"
            predicates:
              - Path=/api/v1/users/**
          - id: notification-service-route
            uri: "lb://NOTIFICATION-SERVICE"
            predicates:
              - Path=/api/v1/notifications/**
