spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:http://config-server:8888"

  kafka:
    bootstrap-servers: kafka:29092
  mail:
    host: mailpit
    port: 1025

app:
  notification:
    templates:
      create:
        subject: "Аккаунт создан!"
        text: "Здравствуйте! Ваш аккаунт на сайте %s был успешно создан."
      delete:
        subject: "Аккаунт удален!"
        text: "Здравствуйте! Ваш аккаунт был удалён."
    variables:
      site-name: ${SITE_NAME:your-site}
