version: '3.3'

services:
  user_service_db:
    image: postgres:16
    container_name: aston-intensive-postgres-main
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_main:/var/lib/postgresql/data

volumes:
  pgdata_main:
