app:
  notification:
    templates:
      create:
        subject: "Аккаунт создан!"
        text: "Здравствуйте! Ваш аккаунт на сайте %s был успешно создан."
      delete:
        subject: "Аккаунт удален!"
        text: "Здравствуйте! Ваш аккаунт был удалён."
    variables:
      site-name: ${SITE_NAME:your-site}

spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://config-server:8888"

  datasource:
    url: jdbc:postgresql://aston-intensive-postgres-main:5432/user_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: spring
    liquibase-schema: public

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: spring
        format_sql: true
