spring.datasource.url=jdbc:postgresql://localhost:5433/user_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.enabled=true
spring.liquibase.default-schema=public
spring.liquibase.liquibase-schema=public
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.jpa.properties.hibernate.default_schema=spring
